parameters:
#    radius_integration.example.class: GarbledTutors\RadiusIntegrationBundle\Example

services:
#    radius_integration.example:
#        class: %radius_integration.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
